## introduction to oop python
   
###  one of the popular approach to solve a programming problem by creating an objects , this is known as Object Oriented Programming


###        An object as two characteristics:
###          1. attributes(name, age, colour)
###           2. Behaviour(learn,study,singing,dance)
###        In Python the concept OOP follow these things:
###           1. Inheritence
###           2. Encapsulation
###           3. Ploymorphism


## Class  :
    ## A class is blueprint for object or logical entity
    
## Object  :
    ## Blueprint of a class or instance of class or physical entity
 
## Methods:
    ## Part of calss and can be called with 
    


class classname:
    # some functions and variables
    # function----used to perform the spesific activity
    # variables--dat(memory)

In [2]:
def test():
    print('Test() for function')
    return
test()

Test() for function


In [5]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj = Demo()
obj.test()

test() for the class and method


In [9]:
class Demo1:
    def fact(self,n):
        #retuen the factorial
        fact = 1
        while(n!=0):
            fact = fact * n
            n=n-1
        return fact
p1 = Demo1()
print(p1.fact(5))

120


In [11]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
c1 = Demo2(10,20)
print(c1.add(100,200))

300


In [14]:
class demo2:
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self,p1,p2):
        print("p1=",p1)
        print("p2=",p2)
c1 = demo2()
c1.accept(10,20)
c1.display(10,20)

p1= 10
p2= 20


In [20]:
# Some Inheritance
# Parent class
class person(object):
    #constructor
    def __init__(self, name):
        self.name = name
    def getname(self):
        return self.name
    def isemployee(self):
        return False

#DERIVED CLASS
class employee(person):
    def isemployee(self):
        return True
      
      
    emp = person("anil")
    print(emp.getname(),emp.isemployee())

    emp = person("akhil")
    print(emp.getname(),emp.isemployee())

    


anil False
akhil False


In [21]:
lst =[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [23]:
import numpy as np
lst = [1,2,3,4]
array = np.array(lst)
print(array)

[1 2 3 4]


In [24]:
lst = [1.0,2.5,3.6,9.5]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [25]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(4,5)])
print(a2.shape)

(2, 3)
(2, 2)


In [27]:
# re-shape the given array
# numpy reshape(array name ,reshape , order='c')
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
# Append Some Data -- Horizontally
# hstack (array1,array2) -- will be automatically arranged
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [29]:
# Append Some Data -- vertically
# vstack (array1,array2) -- will be automatically arranged
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [34]:
# Generate random number from NP
a1 = np.random.normal(5,0.5,10)
print(a1)

[4.8139197  4.30682277 5.36073952 4.48822117 4.75186494 5.1500821
 4.9851408  4.54181644 5.20136551 3.84442981]


In [37]:
#numpy.zeros() and numpy.one()

#generate an array with all zeros --numpy.zeros()

np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [38]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [39]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [40]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2] = 5
print(a)


[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [41]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2][3] = 14
np.asarray(a)[3][3] = 16
print(a)


[[ 1  1  1  1]
 [ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1 16]]


In [43]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [46]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [47]:
# Indexing and Slicing of numpy
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [50]:
a1 = np.array([(1,2,3),(4,5,6)])
print("First Row",a1[0])

First Row [1 2 3]


In [51]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Second Row",a1[1])

Second Row [4 5 6]


In [54]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing Coloum",a1[:,1])

slicing Coloum [2 5]


In [55]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing last coloum",a1[:,2])

slicing last coloum [3 6]


In [56]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Row and Coloum",a1[1:2])

Row and Coloum [[4 5 6]]


In [57]:
a1 = np.random.normal(5,1,10)
print(a1)

[5.86268439 4.40624065 6.10551766 5.4527493  6.66229806 5.31565113
 3.33111004 5.39748273 4.89484133 3.65551393]


## Some Math Operation on given random numbers
### Min      ----returns the least number
### Max      ---returns the large number
### Mean   ---Mean
### Median --Median
### GD       ---Gaussian Distribution


In [58]:
a1 = np.random.normal(5,1,10)
print(a1)
print("Min value = ",np.min(a1))
print("Max value = ",np.max(a1))
print("Mean value = ",np.mean(a1))
print("Median value = ",np.median(a1))

[7.71687492 4.79493246 7.0245031  4.54762369 5.80995721 4.58791273
 4.63892508 4.71325968 4.47824276 3.91905172]
Min value =  3.9190517175861554
Max value =  7.71687492167068
Mean value =  5.223128336205104
Median value =  4.676092381555224


## Pandas Basics

Python is one of the popular programming language for data analysis <br>
python is offering the lib called pandas used for importing and analyzing pretty much faster and easiler

Pandas data for

In [1]:
import pandas as pd
dict ={"name":["Anil","Akhil","dinesh","Harsha","ajay",],
       "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com"],
        "Mobile number":[77,88,99,66,55],
       "Address":["hyd","hyd","hyd","hyd","hyd"]}
b = pd.DataFrame(dict)
print(b)

     name           EmailID  Mobile number Address
0    Anil    anil@gmail.com             77     hyd
1   Akhil   akhil@gmail.com             88     hyd
2  dinesh  dinesh@gmail.com             99     hyd
3  Harsha  harsha@gmail.com             66     hyd
4    ajay    ajay@gmail.com             55     hyd


In [2]:
b.index=["1","2","3","4","5"]
print(b)

     name           EmailID  Mobile number Address
1    Anil    anil@gmail.com             77     hyd
2   Akhil   akhil@gmail.com             88     hyd
3  dinesh  dinesh@gmail.com             99     hyd
4  Harsha  harsha@gmail.com             66     hyd
5    ajay    ajay@gmail.com             55     hyd


# supermarket.csv -Analysis (Which product having higher % of selling)
# which products having least selling %

In [ ]:
import pandas as